package com.epro.mall.mvp.model.bean

data class ShopInfo(val address: String,
                    val area: String,
                    val areaId: Int,
                    val city: String,
                    val cityId: Int,
                    val createTime: String,
                    val distance: String,
                    val email: String,
                    val endTime: String,
                    val id: String,
                    val isRenew: String,
                    val latitude: String,
                    val longitude: String,
                    val mobile: String,
                    val opinions: String,
                    val owner: String,
                    val province: String,
                    val provinceId: Int,
                    val shopDesc: String,
                    var shopDiscount: Float,
                    val shopId: String,
                    val shopImageFive: String,
                    val shopImageFour: String,
                    val shopImageOne: String,
                    val shopImageThree: String,
                    val shopImageTwo: String,
                    val shopLogo: String,
                    val shopName: String,
                    val shopType: String,
                    val shopTypeId: Int,
                    val startTime: String,
                    val status: Int)